# Generated by Django 3.2.16 on 2023-05-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pose', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='Body_part',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='file',
            new_name='File',
        ),
    ]
